#!/usr/bin/python3
"""This module defines a class Square"""


import sys
import math


def factorize(number):
    """
    Factorizes a given number into a product of two smaller numbers.

    Args:
        number (int): The number to factorize.

    Returns:
        str: The factorization of the number in the format "n=p*q".
    """
    for i in range(2, int(math.sqrt(number)) + 1):
        if number % i == 0:
            return f"{number}={i}*{number // i}"
    return f"{number}={number}*1"


if __name__ == "__main__":
    if len(sys.argv) != 2:
        print("Usage: factors <file>")
        sys.exit(1)

    filename = sys.argv[1]

    with open(filename, 'r') as file:
        for line in file:
            number = int(line.strip())
            print(factorize(number))
